### ISSUE TITLE
A0, A1, etc. formats

### ISSUE THREAD

**Issue by MQS-mark** [patrick-kidger/mkposters#11]
Would be great to have templates for other poster sizes (e.g. A0, A1).

**Comment by patrick-kidger** [comment]
I'd be happy to take PR on this!

**Comment by MQS-mark** [comment]
Figured it out now:

When printing (Ctrl+P) in Firefox click on "Print using the system dialogue..." (scroll all the way down) in the pop up window.

Then you can print to (pdf) files and under Page Setup there are more Paper sizes available such as A0 and A1.

I had to only adjust the font sizes etc. in the markdown file and did it with inline CSS to be quick and have everything in the markdown file.

Pretty neat package you made there. One of the biggest pains of researchers are poster presentations and this mkdocs based one is the easiest one I have used so far. And I tried a lot, from org-mode to .js based packages to pure HTML/CSS... and back to Microsoft PowerPoint. Will stick with mkposters now.

**Comment by patrick-kidger** [comment]
Thank you! I'm glad you like it.
